name: Build and Deploy to Azure Env

env:
  AZURE_CONTAINER_REGISTRY: 'acr177185367.azurecr.io'
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.13'               # set this to the node version to use

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
  
permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
      
    runs-on: ubuntu-latest
    needs: [build]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      
          
      - name: showrepo
        run: ls
