name: Build and Deploy to Azure Env

env:
  NODE_VERSION: '18.13'               # set this to the node version to use

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: ['main']
  workflow_dispatch:
  
permissions: 
  contents: read

jobs:
  buildAndtest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./build
    
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
      
    runs-on: ubuntu-latest
    needs: [buildAndtest]
    environment: Production
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./build
      
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      
          
      - name: Azure Static Website
        # You may pin to the exact commit or the version.
        # uses: tibor19/static-website-deploy@b566121f2c83f210fff0b6ed300712bfe2d9ec9f
        uses: tibor19/static-website-deploy@v3
        with:
          # The name of the Azure Storage Account. Make sure to call az login before this step, or provide a value for storage-account-key
          storage-account-name: 'reactdeployjerrytest'
          # One of the two shared keys of the storage account
          storage-account-key: ${{ secrets.Storagekey }}
          # Connection String of the Azure Storage Container
          connection-string: ${{ secrets.Connectionstring }}
          # Name of the Blob Container Storage
          blob-container-name: '$web'
          # Access Policy to update in the Container (container | blob | <none>). For private containers do not specity any value.
          # public-access-policy: # optional

          # If the existing files should be removed before uploading the new files
          remove-existing-files: true

          # Folder containing the files to be uploaded to the Storage Container
          folder: build
