name: pull request

env:
  NODE_VERSION: '18.13'               # set this to the node version to use

run-name: ${{ github.actor }} is asking for a pull request

on:
  pull_request:
    branches: ['main']


jobs:
  buildAndtest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
